package life;
// Generated by makecfg
public interface IRLE {
  public static final int ws = 256;
  public static final int comment = 257;
  public static final int header = 258;
  public static final int runcount = 259;
  public static final int tag = 260;
  public static final int eoln = 261;
  public static final int eofile = 262;
  //
  public static final int FILE = 1000;
  public static final int COMMENTS = 1001;
  public static final int TAGS = 1002;
  public static final int TAG = 1003;
}
