package life;
// Generated by makecfg
public interface IScript {
  public static final int ws = 256;
  public static final int comment = 257;
  public static final int rules = 258;
  public static final int defrules = 259;
  public static final int rulespec = 260;
  public static final int blockspec = 261;
  public static final int intval = 262;
  public static final int blockdata = 263;
  //
  public static final int FILE = 1000;
  public static final int COMMENTS = 1001;
  public static final int RULESPEC = 1002;
  public static final int BLOCKS = 1003;
  public static final int VARRULES = 1004;
  public static final int DEFRULES = 1005;
  public static final int BLOCK = 1006;
}
